accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name='signup'),
]

chat/urls.py
from django.urls import path
from .views import ChatView, IndexView


app_name = 'chat'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('<str:username>/', ChatView.as_view(), name='chat')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('chat.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from accounts.managers import CustomUserManager

from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUserModel(AbstractUser):
    """
    Кастомная модель пользователя
    """

    username = models.CharField(unique=True, max_length=50, blank=True, null=True, verbose_name='Имя пользователя')

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username


class ProfileUserModel(models.Model):
    """
    Модель профиля пользователя
    """

    user = models.OneToOneField(
        "CustomUserModel",
        on_delete=models.CASCADE,
        verbose_name="Профиль",
        related_name="profile",
        blank=True,
        null=True,
    )
    online_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=CustomUserModel)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Сигналы для создания профиля пользователя
    """

    if created:
        ProfileUserModel.objects.create(user=instance)


@receiver(post_save, sender=CustomUserModel)
def save_user_profile(sender, instance, **kwargs):
    """
    Сигналы для сохранения профиля пользователя
    """

    instance.profile.save()

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model

from accounts.models import ProfileUserModel

User = get_user_model()


class RoomChatModel(models.Model):
    """
    Модель комнаты чата
    """

    name = models.CharField(max_length=100, verbose_name='Комната чата')
    user_first = models.ForeignKey(ProfileUserModel, on_delete=models.CASCADE, blank=True,
                                   null=True, verbose_name='Первый пользователь', related_name='user_1')
    user_second = models.ForeignKey(ProfileUserModel, on_delete=models.CASCADE, blank=True,
                                    null=True, verbose_name='Второй пользователь', related_name='user_2')

    class Meta:
        verbose_name = "комната"
        verbose_name_plural = "Комнаты"

    def __str__(self):
        return self.name


class MessageChatModel(models.Model):
    """
    Модель сообщения чата
    """

    sender = models.ForeignKey(ProfileUserModel, on_delete=models.CASCADE, verbose_name='Отправитель')
    message = models.TextField(blank=True, null=True, verbose_name='Сообщение')
    room_name = models.ForeignKey(RoomChatModel, on_delete=models.CASCADE, blank=True, null=True,
                                  verbose_name='Имя комнаты')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.message


class ChatNotificationModel(models.Model):
    """
    Модель уведомлений в чате
    """
    chat = models.ForeignKey(RoomChatModel, on_delete=models.CASCADE, verbose_name='Чат')
    user = models.ForeignKey(ProfileUserModel, on_delete=models.CASCADE, verbose_name='Пользователь')
    is_seen = models.BooleanField(default=False, verbose_name='Статус')

    class Meta:
        verbose_name = "Уведомления"
        verbose_name_plural = "Уведомление"

    def __str__(self) -> str:
        return self.user.user.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUserModel


class CustomUserCreationForm(UserCreationForm):
    """
    Форма регистрации пользователя
    """

    class Meta:
        model = CustomUserModel
        fields = ['username', 'email', ]
        labels = {
            'username': 'Имя пользователя',
            'email': 'Электронная почта',
        }

accounts/views.py
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView

from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CustomUserCreationForm

from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpView(CreateView):
    """
    Регистрация пользователя
    """

    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from django.contrib.auth import get_user_model

from .services import create_chat_name, get_list_rooms_users, get_chat_room
from .models import MessageChatModel, RoomChatModel
from accounts.models import ProfileUserModel

User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    """
    Представление домашней страницы
    """

    template_name = 'chat/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.exclude(username=self.request.user.username)
        return context


class ChatView(LoginRequiredMixin, TemplateView):
    """
    Представление чата
    """

    template_name = 'chat/chat_main.html'

    def get_context_data(self, **kwargs):
        user = User.objects.get(username=self.kwargs['username'])

        room_name = create_chat_name(
            user_1=self.request.user.id,
            user_2=user.id,
        )

        room = get_chat_room(
            room_name=room_name,
            user_1=self.request.user,
            user_2=user
        )

        users_with_chat_names = get_list_rooms_users(self.request.user)

        context = super().get_context_data(**kwargs)
        context['users'] = users_with_chat_names
        context['user'] = user
        context['messages'] = MessageChatModel.objects.filter(room_name=room)
        context['room_name'] = room_name
        return context

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Вход{% endblock %}
{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">{% endblock %}

{% block content %}
<div class="login-container">
    <div class="login-form">
        <h2>Вход</h2>
        {% if request.user.is_authenticated %}
        <h3>Вы уже авторизованы</h3>
        <a href="/">Назад</a>
        {% else %}
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.label }}">
                {% endfor %}
                {% if form.non_field_errors %}
                    <p class="error">
                        {{ form.non_field_errors.0 }}
                    </p>
                {% endif %}
                <button type="submit">Вход</button>
            </form>
        <a href="{% url 'accounts:signup' %}">Регистрация</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock %}
{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">{% endblock %}

{% block content %}
<div class="login-container">
    <div class="login-form">
        <h2>Регистрация</h2>
        {% if request.user.is_authenticated %}
            <h3>Вы уже прошли регистрацию</h3>
            <a href="/">Назад</a>
        {% else %}
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.label }}">
<!--                    {% if field.name == 'password' %}-->
<!--                        <input type="password" placeholder="{{ field.label|lower }}" required>-->
<!--                    {% else %}-->
<!--                        <input placeholder="{{ field.label|lower }}">-->
<!--                    {% endif %}-->

                    {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                <button type="submit">Зарегистрироваться</button>
            </form>
        <a href="{% url 'accounts:login' %}">Вход</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Заголовок страницы{% endblock %}</title>
    {% block static %}<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">{% endblock %}
</head>

<body>
<!--<header>-->
<!--    <div class="header-title">-->
<!--    </div>-->
<!--    <div class="header-actions">-->
<!--        <a href="">Настройки</a> |-->
<!--        <a href="">Выход</a>-->
<!--    </div>-->
<!--</header>-->
{% block content %}
{% endblock %}
</body>
</html>

templates/chat/chat_main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Чат{% endblock %}

{% block content %}
<div class="chat-container">
    <div class="user-list">
        <div class="header">
            <h3>Пользователи</h3>
        </div>
        <ul>
            {% for p in users %}
            <li class="user">
                <div class="user-avatar">
                    <img src="{% static 'assets/dp.png' %}" alt="User Avatar">
                </div>
                {% if p.online_status %}
                    <div class="user-info">
                        <a style="color: green" id="{{p.user.username}}_status" href="{% url 'chat:chat' username=p.user.username %}">{{p.user.username}}</a>
                    </div>
                {% else %}
                    <div class="user-info">
                        <a style="color: grey" id="{{p.user.username}}_status" href="{% url 'chat:chat' username=p.user.username %}">{{p.user.username}}</a>
                    </div>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="chat">
        <div class="header">
            <div class="user-avatar">
                <img src="{% static 'assets/dp.png' %}" alt="User Avatar">
            </div>
            <h2>{{ user.username }}</h2>
        </div>
        <div class="chat-messages" id="chat-messages">
            {% for message in messages %}
            <div class="message {% if message.sender == request.user.profile %}sent{% else %}received{% endif %}">
                <div class="message-text">
                    {{ message }}
                </div>
                <div class="message-date">
                    {{message.timestamp|time:'H:i'}}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="chat-input">
            <input type="text" id="message-input" placeholder="Введите сообщение">
            <button type="submit" id="chat-message-submit">Отправить</button>
        </div>
    </div>
</div>

{{ user.id|json_script:"json-username" }}
{{ user.username|json_script:"json-username-receiver" }}
{{ request.user.username|json_script:"json-message-username" }}
{{ request.user.id|json_script:"json-user-id"}}
{{ room_name|json_script:"json-room-name"}}
<script src="{% static 'js/chat.js' %}"></script>
<script src="{% static 'js/online_status.js' %}"></script>
<script src="{% static 'js/notifications.js' %}"></script>
{% endblock %}

templates/chat/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Чат{% endblock %}

{% block content %}
<div class="chat-container">
    <div class="user-list">
        <div class="header">
            <h3>Пользователи</h3>
        </div>
        <ul>
            {% for user in users %}
            <li class="user">
                <div class="user-avatar">
                    <img src="{% static 'assets/dp.png' %}" alt="User Avatar">
                </div>
                {% if user.profile.online_status %}
                    <div class="user-info">
                        <a style="color: green" id="{{user.username}}_status" href="{% url 'chat:chat' username=user.username %}">{{user.username}}</a>
                    </div>
                {% else %}
                    <div class="user-info">
                        <a style="color: grey" id="{{user.username}}_status" href="{% url 'chat:chat' username=user.username %}">{{user.username}}</a>
                    </div>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="chat">
        <div class="header">
            <div class="user-avatar">
                <img src="{% static 'assets/dp.png' %}" alt="User Avatar">
            </div>
            <h2>{{ user.username }}</h2>
        </div>
        <div class="chat-messages" id="chat-messages">
            {% for message in messages %}
            <div class="message {% if message.sender == request.user.profile %}sent{% else %}received{% endif %}">
                <div class="message-text">
                    {{ message }}
                </div>
                <div class="message-date">
                    {{message.timestamp|time:'H:i'}}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="chat-input">
            <input type="text" id="message-input" placeholder="Введите сообщение">
            <button type="submit" id="chat-message-submit">Отправить</button>
        </div>
    </div>
</div>
{{ user.id|json_script:"json-username" }}
{{ user.username|json_script:"json-username-receiver" }}
{{ request.user.username|json_script:"json-message-username" }}
{{ request.user.id|json_script:"json-user-id"}}
<script src="{% static 'js/chat.js' %}"></script>
<script src="{% static 'js/online_status.js' %}"></script>
{% endblock %}